#!/usr/bin/env bash

Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    PubkeyAuthentication yes
